name: 'my_dbt_project'
version: '1.0.0'
config-version: 2

profile: 'my_profile'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
data-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory for compiled SQL and results
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_modules"

models:
  my_dbt_project:
    +materialized: view