version: 1
type: topic
base_view: ltv
model_name: pure_organics
label: My LTV
views:
  customers:
    join:
      join_type: left_outer
      relationship: one_to_many
      sql_on: ${ltv.CUSTOMER_ID}=${customers.accepts_marketing}
