version: 1
type: view
name: products
model_name: pure_organics
sql_table_name: DEMO_PROD.PRODUCTS
row_label: Product
identifiers:
  - name: product_id
    type: primary
    sql: ${product_id}
fields:
  - name: product_id
    field_type: dimension
    type: string
    hidden: true
    primary_key: true
    sql: ${TABLE}.PRODUCT_ID
    zoe_description: The id of the product.
  - name: ''
    field_type: measure
    type: sum
    value_format_name: decimal_0
    sql: null
