version: 1
type: view
name: products
model_name: pure_organics
sql_table_name: DEMO_PROD.PRODUCTS
fields:
  - name: product_id
    field_type: dimension
    type: string
    sql: ${TABLE}."PRODUCT_ID"
    searchable: true

  - name: product_type
    field_type: dimension
    type: string
    sql: ${TABLE}."PRODUCT_TYPE"
    searchable: true

  - name: product_title
    field_type: dimension
    type: string
    sql: ${TABLE}."PRODUCT_TITLE"
    searchable: true

  - name: price
    field_type: dimension
    type: number
    sql: ${TABLE}."PRICE"
