version: 1
type: view
name: products
model_name: pure_organics
sql_table_name: DEMO_PROD.PRODUCTS
row_label: Product
identifiers:
  - name: product_id
    type: primary
    sql: ${product_id}
fields:
  - name: product_id
    field_type: dimension
    type: string
    hidden: true
    primary_key: true
    sql: ${TABLE}.PRODUCT_ID
    zoe_description: The id of the product.
  - name: product_type
    field_type: dimension
    type: string
    description: 'The type of the product sold (Eye, Face, Lip, etc) '
    sql: ${TABLE}.PRODUCT_TYPE
    searchable: true
    zoe_description: 'The type of the product. '
  - name: product_title
    field_type: dimension
    type: string
    description: The title of the product sold (Everyday SPF Cream, etc)
    sql: ${TABLE}.PRODUCT_TITLE
    tags:
      - product
    searchable: true
  - name: price
    field_type: dimension
    type: string
    description: Blahabababbaba
    sql: ${TABLE}.PRICE
    searchable: true
  - name: product_image_url
    field_type: dimension
    type: string
    value_format_name: decimal_0
    sql: |-
      product_id,
             product_type,
             product_title,
             price,
             case
                 when product_id = 'P1' then 'https://example.com/image_P5.jpg'
                 when product_id = 'P2' then 'https://example.com/image_P5.jpg'
                 when product_id = 'P3' then 'https://example.com/image_P5.jpg'
                 when product_id = 'P4' then 'https://example.com/image_P5.jpg'
                 when product_id = 'P5' then 'https://example.com/image_P5.jpg'
                 when product_id = 'P6' then 'https://example.com/image_P5.jpg'
                 when product_id = 'P7' then 'https://example.com/image_P5.jpg'
                 when product_id = 'P8' then 'https://example.com/image_P5.jpg'
                 when product_id = 'P9' then 'https://example.com/image_P5.jpg'
                 when product_id = 'P10' then 'https://example.com/image_P5.jpg'
                 when product_id = 'P11' then 'https://example.com/image_P5.jpg'
                 when product_id = 'P12' then 'https://example.com/image_P5.jpg'
                 else 'https://example.com/image_P5.jpg'
             end as product_image_url
      from DEMO_PROD.PRODUCTS;
    description: image url
    searchable: true
