version: 1
type: view
name: products
model_name: pure_organics
sql_table_name: DEMO_PROD.PRODUCTS
row_label: Product
identifiers:
  - name: product_id
    type: primary
    sql: ${product_id}
fields:
  - name: product_id
    field_type: dimension
    type: string
    hidden: true
    primary_key: true
    sql: ${TABLE}.PRODUCT_ID
    zoe_description: The id of the product.
  - name: product_type
    field_type: dimension
    type: string
    description: 'The type of the product sold (Eye, Face, Lip, etc) '
    sql: ${TABLE}.PRODUCT_TYPE
    searchable: true
    zoe_description: 'The type of the product. '
  - name: product_title
    field_type: dimension
    type: string
    description: The title of the product sold (Everyday SPF Cream, etc)
    sql: ${TABLE}.PRODUCT_TITLE
    tags:
      - product
    searchable: true
  - name: price
    field_type: dimension
    type: string
    description: Blahabababbaba
    sql: ${TABLE}.PRICE
    searchable: true
  - name: product_image_url
    field_type: dimension
    type: string
    value_format_name: decimal_0
    sql: |2
          products_product_id,
          products_category,
          products_product_name,
          products_price,
          CASE
              WHEN products_product_id = 'P1' THEN 'https://example.com/image_P1.jpg'
              WHEN products_product_id = 'P2' THEN 'https://example.com/image_P2.jpg'
              WHEN products_product_id = 'P3' THEN 'https://example.com/image_P3.jpg'
              WHEN products_product_id = 'P4' THEN 'https://example.com/image_P4.jpg'
              WHEN products_product_id = 'P5' THEN 'https://example.com/image_P5.jpg'
              WHEN products_product_id = 'P6' THEN 'https://example.com/image_P6.jpg'
              WHEN products_product_id = 'P7' THEN 'https://example.com/image_P7.jpg'
              WHEN products_product_id = 'P8' THEN 'https://example.com/image_P8.jpg'
              WHEN products_product_id = 'P9' THEN 'https://example.com/image_P9.jpg'
              WHEN products_product_id = 'P10' THEN 'https://example.com/image_P10.jpg'
              WHEN products_product_id = 'P11' THEN 'https://example.com/image_P11.jpg'
              WHEN products_product_id = 'P12' THEN 'https://example.com/image_P12.jpg'
              ELSE 'https://example.com/default_image.jpg'
          END AS product_image_url
      FROM 
          Products;
    description: image url
    searchable: true
