version: 1
type: view
name: product
model_name: pure_organics
sql_table_name: DEMO_PROD.PRODUCTS
row_label: Product
identifiers:
  - name: product_id
    type: primary
    sql: ${product_id}
fields:
  - name: testing
    field_type: dimension
    type: string
    hidden: 'yes'
    primary_key: 'yes'
    sql: ${TABLE}.PRODUCT_ID
