version: 1
type: view
name: products
model_name: pure_organics
sql_table_name: DEMO_PROD.PRODUCTS
row_label: Product
identifiers:
  - name: primary type
    type: primary
    sql: ${product_id}
  - name: foreign type
    type: foreign
    sql: ${price}
  - name: join type
    sql: ''
    type: join
always_filter: []
fields:
  - name: product_id
    field_type: dimension
    type: string
    hidden: yes
    primary_key: yes
    sql: ${TABLE}.PRODUCT_ID
    zoe_description: The id of the product.
    filters:
      - field: f0
        value: v0
      - field: f1
        value: v1
      - field: f2
        value: v2
  - name: product_type
    field_type: dimension
    type: string
    description: 'The type of the product sold (Eye, Face, Lip, etc) '
    sql: ${TABLE}.PRODUCT_TYPE
    searchable: true
    zoe_description: 'The type of the product. '
  - name: product_title
    field_type: dimension
    type: string
    description: The title of the product sold (Everyday SPF Cream, etc)
    sql: ${TABLE}.PRODUCT_TITLE
    tags:
      - product
    searchable: true
  - name: price
    field_type: dimension
    type: string
    description: Blahabababbaba
    sql: ${TABLE}.PRICE
