version: 1
type: view
name: product_facts
model_name: pure_organics
default_date: order
identifiers:
- name: primkey
  type: primary
  sql: ${primkey}

fields:
- name: primkey
  field_type: dimension
  type: string
  hidden: true
  primary_key: true
  sql: concat(${order_raw}||${product_type})
  searchable: false

- name: product_title
  field_type: dimension
  type: string
  sql: ${TABLE}.product_title
  searchable: true

- name: product_type
  field_type: dimension
  type: string
  sql: ${TABLE}.product_type
  searchable: true

- name: order
  field_type: dimension_group
  type: time
  datatype: timestamp
  label: Order Date
  description: The time at which the order was placed. This is the main time field
    to use for orders
  timeframes:
  - raw
  - date
  - week_index
  - week
  - month_of_year
  - month
  - quarter
  - year
  sql: ${TABLE}.order_at

- name: number_of_orders
  field_type: measure
  type: sum
  sql: ${TABLE}.number_of_orders

- name: number_of_units
  field_type: measure
  type: sum
  sql: ${TABLE}.number_of_units

- name: total_cogs
  field_type: measure
  type: sum
  sql: ${TABLE}.total_cogs
derived_table:
  sql: "select order_lines.order_at\n      ,product_title as product_title\n     \
    \ ,product_type as product_type\n      ,count(distinct order_lines.order_id) as
    number_of_orders\n      ,sum(order_lines.quantity) as number_of_units\n      ,sum(order_lines.cogs)
    as total_cogs\nfrom DEMO_PROD.ORDER_LINES order_lines left join DEMO_PROD.PRODUCTS
    products on order_lines.product_id = products.product_id group by order_lines.order_at\n\
    \        ,products.product_title\n        ,products.product_type\n"
