version: 1
type: view
name: products
model_name: pure_organics
sql_table_name: DEMO_PROD.PRODUCTS
row_label: Product
identifiers:
  - name: product_id
    type: primary
    sql: ${product_id}
fields:
  - name: product_id
    field_type: dimension
    type: string
    hidden: true
    primary_key: true
    sql: ${TABLE}.PRODUCT_ID
    zoe_description: The id of the product.
    description: The id of the product.
  - name: product_type
    field_type: dimension
    type: string
    description: 'The type of the product sold (Eye, Face, Lip, etc) '
    sql: ${TABLE}.PRODUCT_TYPE
    searchable: true
    zoe_description: 'The type of the product. '
  - name: product_title
    field_type: dimension
    type: string
    description: The title of the product sold (Everyday SPF Cream, etc)
    sql: ${TABLE}.PRODUCT_TITLE
    tags:
      - product
    searchable: true
  - name: price
    field_type: dimension
    type: string
    description: Blahabababbaba
    sql: ${TABLE}.PRICE
    searchable: true
  - name: product_image_url
    field_type: dimension
    type: string
    value_format_name: image_from_url
    sql: >+
      CASE ${product_type}

      WHEN 'Face' THEN
      'https://www.apple.com/v/tv-home/n/images/overview/hero__dbphk49ymi2q_large.jpg'

      WHEN 'Eye' THEN
      'https://www.apple.com/v/iphone-15/c/images/overview/ecosystem/airpods__cs4xf14itggi_large.jpg'

      WHEN 'Lip' THEN
      'https://media4.giphy.com/media/v1.Y2lkPTc5MGI3NjExNjU4dnB5ZDhxMDlqdXRkN2l2YmlzMTdwNjE0emJpaHNzeHNwYmRlNCZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/vFKqnCdLPNOKc/giphy.webp'

      ELSE
      'https://www.apple.com/v/iphone-15/c/images/overview/usb-c/usbc__bvuxditgibci_large.png'

      END

    description: my image url
    searchable: true
