base_view: basic_data_table
model_name: pure_organics
label: Basic Data Table
description: >-
  This is a table description. This is a table description. This is a table
  description. This is a table description. This is a table description. This is
  a table description. This is a table description. This is a table
  description. 
views: {}
type: topic
