base_view: candy_shop_orders2
model_name: zenlytic_managed
label: Candy Shop Orders2
description: ''
views:
  candy_shop_order_items2:
    join:
      join_type: left_outer
      relationship: one_to_many
      sql_on: ${candy_shop_orders2.order_id}=${candy_shop_order_items2.order_id}
type: topic
