type: topic
label: Customer Overview
base_view: customers
model_name: pure_organics
description: The Customer Overview view offers detailed insights into the customer
  data for Pure Organics. It includes key information like customer IDs, contact details,
  and marketing preferences. This view helps identify whether a customer accepts marketing
  communications and tracks their initial engagement with marketing initiatives. It
  provides fields for customer identification, including full name, address, and location,
  as well as first interaction details such as first marketing group, promotion, campaign,
  and order. Use this data for analyzing customer behavior, improving acquisition
  and retention strategies, and optimizing marketing efforts.
zoe_description: The Customer Overview view contains essential fields for analyzing
  customer information at Pure Organics. It includes customer IDs, names, contact
  information, and their consent to receive marketing communications. This view tracks
  initial customer interactions with marketing strategies and orders, which aids in
  understanding customer behavior and optimizing marketing strategies.
hidden: false
views: {}
