type: topic
label: Customers
base_view: customers
model_name: pure_organics
description: Customer data
zoe_description: Customer data
hidden: false

views:
  customers:
    join:
      join_type: left_outer
      relationship: one_to_many
      sql_on: ${customers.customer_id} = ${order_lines.customer_id}