type: topic
label: Marketing Spend Analysis
base_view: marketing_spend
model_name: pure_organics
description: This view encapsulates data related to marketing expenses across various
  channels and sources. It provides insights into different campaigns by detailing
  the total marketing spend, cost per acquisition (CAC), cost per click (CPC), return
  on ad spend (ROAS), and profit on ad spend (PROAS). Key fields include the marketing
  channel, the source of spend, and specific campaign identifiers, all crucial for
  analyzing the efficiency and effectiveness of marketing investments.
zoe_description: This view provides detailed insights into marketing expenditures
  by channel and source. It includes metrics such as total spend, CAC, CPC, ROAS,
  and PROAS, which can be used to evaluate campaign success and optimize marketing
  strategies.
hidden: false
views: {}
