base_view: marvel_rivals_heroes2
model_name: zenlytic_managed
label: Marvel Rivals Heroes2
description: ''
views:
  marvel_rivals_abilities2:
    join:
      join_type: left_outer
      relationship: one_to_many
      sql_on: ${marvel_rivals_heroes2.hero_id}=${marvel_rivals_abilities2.hero_id}
type: topic
