base_view: customers_list
model_name: pure_organics
label: new topic
views:
  customers:
    join:
      join_type: left_outer
      relationship: many_to_one
      sql_on: ${customers_list.CUSTOMER_ID}=${customers.CUSTOMER_ID}
type: topic
