type: topic
label: Order Analysis
base_view: order_lines
model_name: pure_organics
description: This data model represents a detailed breakdown of order lines, helping
  analyze marketing influences and revenue outcomes. Key fields include 'ORDER_ID,'
  identifying unique orders, and 'CAMPAIGN' and 'PROMOTION,' indicating marketing
  strategies linked to each order. The model differentiates between 'SUBSCRIPTION_VS_OTP'
  to track subscription versus one-time purchases, and includes 'MARKETING_SOURCE'
  and 'CHANNELS' for attribution insights. Revenue fields such as 'TOTAL_GROSS_REVENUE'
  and 'TOTAL_NET_REVENUE' help evaluate financial performance. The model also measures
  customer behavior and purchasing patterns through 'NEW_VS_REPEAT,' and detailed
  metrics like 'REPURCHASE_RATE' and 'NET_MARGIN,' supporting strategy optimization
  across marketing and sales.
zoe_description: This model analyzes order data, providing insights into marketing
  efficacy and financial results. It covers identifiers like 'ORDER_ID' and marketing
  details ('CAMPAIGN,' 'PROMOTION'), distinguishing between 'SUBSCRIPTION_VS_OTP.'
  Channels and sources are detailed for attribution. Revenue metrics ('TOTAL_GROSS_REVENUE,'
  'NET_REVENUE') measure financial outcomes. Customer purchasing behavior is characterized
  by 'NEW_VS_REPEAT' and metrics like 'REPURCHASE_RATE.' Use this model to refine
  marketing strategies and enhance sales performance.
hidden: false
views:
  products:
    join:
      join_type: left_outer
      relationship: many_to_one
      sql_on: ${order_lines.product_id}=${products.product_id}
