base_view: LTV
label: Promotion
model_name: zenlytic_managed
views:
  products:
    join:
      join_type: inner
      relationship: one_to_one
      sql_on: ${LTV.GROSS_SALES}=${products.product_id}
type: topic
