type: topic
label: Sales and Product Metrics
base_view: sample_derived_table
model_name: pure_organics
description: The 'Sales and Product Metrics' dataset provides insights into sales
  performance and inventory. It includes details such as 'PRODUCT_TITLE' and 'PRODUCT_TYPE'
  for categorizing items. Key metrics include 'NUMBER_OF_ORDERS' capturing the frequency
  of product purchases, 'NUMBER_OF_UNITS' detailing the total quantity sold, and 'TOTAL_COGS'
  (Cost of Goods Sold) indicating the direct costs tied to these sales. This data
  is useful for identifying top-selling products and optimizing stock management and
  pricing strategies.
zoe_description: Interpret 'Sales and Product Metrics' to analyze sales performance.
  Focus on 'PRODUCT_TITLE' and 'PRODUCT_TYPE' for categorization. Use 'NUMBER_OF_ORDERS'
  and 'NUMBER_OF_UNITS' to assess sales volume and performance, alongside 'TOTAL_COGS'
  for evaluating cost efficiency and profitability.
hidden: false
views: {}
