base_view: sample_data
model_name: pure_organics
label: Sample Data
description: >-
  This is a description. This is a description. This is a description. This is a
  description. This is a description. This is a description. This is a
  description. This is a description. This is a description. This is a
  description. 
views: {}
type: topic
