base_view: sample_data
description: >-
  This is a description. This is a description. This is a description. This is a
  description. This is a description. This is a description. This is a
  description. This is a description. This is a description. This is a
  description. 
label: Sample Data
model_name: pure_organics
views: {}
type: topic
