type: topic
label: Session Data
base_view: events
model_name: pure_organics
hidden: false

views:
  events:
    join:
      join_type: left_outer
      join_as: events_two
      relationship: many_to_one
      sql_on: ${events.session_id}=${events.session_id}