type: topic
label: User Events Metadata
base_view: events
model_name: pure_organics
description: This dataset captures detailed metadata about user-generated events on
  a platform. Each event record includes information about the user's device capabilities
  (such as if it is mobile and the device type), the marketing channel through which
  the user arrived, UTM parameters (medium, source, campaign), and promotions. It
  also includes browser-specific details like user agent, language, and name, alongside
  geographic details (country, region, latitude, longitude, timezone). OS information,
  the referer URL, event names and sequences, as well as session statistics, help
  track user interaction comprehensively.
zoe_description: This topic captures metadata about user events, including device
  details, marketing channels, and geographic information. For example, 'events.DEVICE_IS_MOBILE'
  indicates if a device is mobile, while 'events.MARKETING_CHANNEL' denotes the marketing
  channel. UTM parameters provide campaign info. Browser and OS details specify the
  user environment. Use this information to analyze user interaction and behavior.
hidden: false
views: {}
